### ISSUE TITLE
Watching Account Changes

### ISSUE THREAD

**Issue by mudgen** [district0x/re-frame-web3-fx#3]
I see that you can watch balance changes with :web3/get-balances.

How do you watch account (the current ethereum address being used) changes?

**Comment by madvas** [comment]
For ETH balance it polls the balance on every new block

**Comment by mudgen** [comment]
Yes, I see that, but that is not my question.  My question is, how do you poll the current account that is being used?  Not the balance.

**Comment by mudgen** [comment]
For example,  I change the account I am using in MetaMask,  what is the best way to use re-frame-web3-fx to detect that change?

**Comment by mudgen** [comment]
How should I poll for account changes?

**Comment by mudgen** [comment]
Currently I am polling for account changes by using an interval effect handler that I wrote that uses js/setInterval to dispatch an event that uses the web3/call effect handler that calls web3-eth/accounts.  Is that how you do it?

**Comment by madvas** [comment]
Yes, this library know about your current account. You need to first load it with `cljs-web3.eth/accounts` and then pass it into `:web3/get-balances`

**Comment by mudgen** [comment]
Yes, and when the account changes how does my application know when to call cljs-web3.eth/accounts again?

**Comment by mudgen** [comment]
Do you repeatedly call cljs-web3.eth/accounts on a timer to make sure you always have the current account?

**Comment by madvas** [comment]
Yes, currently you need to do it by polling every x seconds. Sadly, Metamask currently doesn't provide event to listen on account changes

**Comment by mudgen** [comment]
Okay, thanks!   I am finding re-frame-web3-fx and cljs-web3 to be very useful, thanks for making it available.
