### ISSUE TITLE
the callback made by `web3-eth/get-transaction-receipt` was not called when web3 receive receipt.

### ISSUE THREAD

**Issue by cmal** [district0x/re-frame-web3-fx#5]
The callback function, which is the last parameter of `web3-eth/get-transaction-receipt`, was not triggered when web3 receive a transaction receipt.

**Comment by cmal** [comment]
Code is here : https://github.com/cmal/eth-tweet-shadow
# MetaMask received the response, but only `:new-tweet/confirmed` runned.

![image](https://user-images.githubusercontent.com/1773318/37565567-7711e6b8-2ae6-11e8-90fa-84c68da0c2f2.png)

# I debugged this, and found `dispatch-on-tx-receipt-fn` had run, but the `fn` it returns were not called.

![image](https://user-images.githubusercontent.com/1773318/37565571-936cdfe8-2ae6-11e8-9c33-34caeb45cb1c.png)

![image](https://user-images.githubusercontent.com/1773318/37565558-4a585c92-2ae6-11e8-9051-826e156cfa5e.png)
![image](https://user-images.githubusercontent.com/1773318/37565560-50e3b02a-2ae6-11e8-8818-0420f3a70185.png)
![image](https://user-images.githubusercontent.com/1773318/37565561-5513025e-2ae6-11e8-93fe-a735f3da6d4f.png)

**Comment by mudgen** [comment]
I am running into this same issue, what can be done?

**Comment by mudgen** [comment]
For me the on-tx-hash function/event gets dispatched like it should. However the on-tx-success and on-tx-receipt functions/events do not get dispatched.

I am using Ganache version v1.1.0-beta.1 - Candy Apple and I am using MetaMask.

**Comment by mudgen** [comment]
I also tested this with Ganache version v1.0.2 and the Rinkeby test network using MetaMask. Same issue.

**Comment by mudgen** [comment]
I restarted my web browser and then it started working. It seems to be a problem with MetaMask, because restarting my web browser fixed it.

**Comment by cmal** [comment]
Weird. The metamask itself can get the receipt. It seems not a problem of this library.

BANG! I restart my chrome and it works. Thanks @mudgen !
